version: '3'

services:

  db:
    image: "postgres" 
    env_file: 
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5430:5432"
  
  backend:
    image: "4rent"
    env_file: 
      - .env
    container_name: 4rent
    depends_on: 
      - db
    network_mode: host
